### ISSUE TITLE
ARMI Installation Clarification. 

### ISSUE THREAD

**Issue by slangfo1** [terrapower/terrapower.github.io#1]
The instructions for installation under the quick start guide includes the following command line snip-it.
```
$ git clone https://github.com/terrapower/armi
$ pip install -r requirements.txt
$ python setup.py install
$ armi
```
However, following these instructions explicitly will result in a file not found error when performing `pip install -r requirements.txt` since the `requirements.txt ` is within the armi folder. This can be alleviated by instructing the user to cd into the armi folder before attempting to perform the `pip install -r requirements.txt` step.

This should also be clarified under the the installation chapter of the user guide.

**Comment by ntouran** [comment]
Thanks so much for finding and reporting that! I just pushed the fix.
